apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydemoapp
spec:
  selector:
    matchLabels:
      app: mydemoapp
  replicas: 1
  template:
    metadata:
      labels:
        app: mydemoapp
    spec:
      containers:
        - name: mydemoapp
          imagePullPolicy: Never
          image: deepthylalithatech/mydemoapp:1.0.0
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 25m
              memory: 10Mi
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mydemoapp
spec:
  type: NodePort
  selector:
    app: example
  ports:
    - port: 8080
      targetPort: 8080
