apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: default
  labels:
      app: java-app
spec:
  selector:
    matchLabels:
      app: java-app
  replicas: 1
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: "deepthylalithatech/mydemoapp:latest"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: java-app
  ports:
    - port: 9090
      targetPort: 8080
      
