name: Build Maven Project and Push Docker Image

on:

  workflow_dispatch:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build Maven project
        run: mvn clean install

      - name: Set up Docker
        uses: docker/setup-docker@v2

      - name: Build Docker image
        run: docker build -t my-docker-image .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push my-docker-image
