name: Build Maven Project and Push Docker Image

on:

  workflow_dispatch:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Maven project
        run: mvn clean install

    
