name: Build Maven Project and Push Docker Image

on:

  workflow_dispatch:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Maven project
        run: mvn clean install

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push Docker image
        run: |
          
            docker build -t deepthylalithatech/mydemoapp:1.0.0 .
            docker push deepthylalithatech/mydemoapp:1.0.0

      - name: Start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
        with:

          driver: docker
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build image
        run: |
            export SHELL=/bin/bash
            eval $(minikube -p minikube docker-env)
            docker build -f ./Dockerfile -t deepthylalithatech/mydemoapp:1.0.0 .
            echo -n "verifying images:"
            docker images
      - name: Deploy to Minikube
        run: kubectl apply -f deploy-to-minikube.yaml
      - name: LOGS
        run: minikube logs --file=logs.txt
      - name: Test service URLs
        run: |
          minikube service list
          minikube service java-app --url
          echo "------------------opening the service------------------"
          curl $(minikube service java-app --url)


